[gemma_servers]
# Remplace par l'IP/host de ton serveur dédié OVH
gemma-gpu-01 ansible_host=141.94.35.54 ansible_user=ubuntu

[gemma_servers:vars]
ansible_python_interpreter=/usr/bin/python3
# Si connexion en root direct : ansible_user=root et retire --ask-become-pass
